// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AttachToAppPoolProcessExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "AttachToAppPoolProcessExtension.3f4faf03-896c-4996-a482-a02eabc4cdde";
        public const string Name = "AttachToAppPoolProcessExtension";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "KMD A/S";
        public const string Tags = "";
    }
}
