// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AttachToAppPoolProcessExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "AttachToAppPoolProcessExtension.3f4faf03-896c-4996-a482-a02eabc4cdde";
        public const string Name = "Attach To App Pool Process Toolbar";
        public const string Description = @"Toolbar providing an easy way to attach to predefined IIS processes based on the name of the associated App Pool.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Krzysztof Koźlik";
        public const string Tags = "Attach, Attach to process, Attach toolbar, Debug, Debugger, Debugging, Menus and Toolbars, IIS, App Pool";
    }
}
