// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AttachToAppPoolProcessExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "AttachToAppPoolProcessExtension.3f4faf03-896c-4996-a482-a02eabc4cdde";
        public const string Name = "Attach To App Pool Process";
        public const string Description = @"Extension providing an easy way to attach to predefined IIS processes based the name of the App Pool they belong to.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "KMD A/S";
        public const string Tags = "";
    }
}
