// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AttachToAppPoolProcessExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string AttachToAppPoolProcessExtensionString = "f3886817-e648-4d25-9d91-4ecd660fa3aa";
        public static Guid AttachToAppPoolProcessExtension = new Guid(AttachToAppPoolProcessExtensionString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int Toolbar = 0x2000;
        public const int ToolbarGroup = 0x2050;
        public const int OpenOptionsCommand = 0x3000;
        public const int AppPoolProcessComboCommand = 0x3001;
        public const int AppPoolProcessComboListCommand = 0x3002;
        public const int AttachToProcessCommand = 0x3003;
    }
}